package TablasBD;
// Generated 09-ago-2017 11:57:13 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
@SuppressWarnings({"serial", "rawtypes"})
public class Factura implements java.io.Serializable {

	private Integer id;
	private UsuariosLogin usuariosLogin;
	private Clientes clientes;
	private Date fecha;
	private Date fechaPago;
	private Date fechaEntrega;
	private int prendas;
	private int perchas;
	private float total;
	private boolean estado;
	private Set percheros = new HashSet(0);

	public Factura() {
	}

	public Factura(UsuariosLogin usuariosLogin, Clientes clientes, Date fecha, Date fechaPago, int prendas, int perchas, float total, boolean estado) {
		this.usuariosLogin = usuariosLogin;
		this.clientes = clientes;
		this.fecha = fecha;
		this.fechaPago = fechaPago;
		this.prendas = prendas;
		this.perchas = perchas;
		this.total = total;
		this.estado = estado;
	}

	public Factura(UsuariosLogin usuariosLogin, Clientes clientes, Date fecha, Date fechaPago, Date fechaEntrega,
			int prendas, int perchas, float total, boolean estado) {
		this.usuariosLogin = usuariosLogin;
		this.clientes = clientes;
		this.fecha = fecha;
		this.fechaPago = fechaPago;
		this.fechaEntrega = fechaEntrega;
		this.prendas = prendas;
		this.perchas = perchas;
		this.total = total;
		this.estado = estado;
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UsuariosLogin getUsuariosLogin() {
		return this.usuariosLogin;
	}

	public void setUsuariosLogin(UsuariosLogin usuariosLogin) {
		this.usuariosLogin = usuariosLogin;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	public int getPrendas() {
		return this.prendas;
	}

	public void setPrendas(int prendas) {
		this.prendas = prendas;
	}

	public int getPerchas() {
		return this.perchas;
	}

	public void setPerchas(int perchas) {
		this.perchas = perchas;
	}

	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	public Set getPercheros() {
		return this.percheros;
	}

	public void setPercheros(Set percheros) {
		this.percheros = percheros;
	}

}
