package TablasBD;
// Generated 12-abr-2017 22:29:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura implements java.io.Serializable {

	private Integer id;
	private Clientes clientes;
	private Date fecha;
	private Date fechaPago;
	private Date fechaEntrega;
	private int prendas;
	private int perchas;
	private float total;
	private boolean estado;

	public Factura() {
	}

	public Factura(Clientes clientes, Date fecha, Date fechaPago, int prendas, int perchas, float total, boolean estado) {
		this.clientes = clientes;
		this.fecha = fecha;
		this.fechaPago=fechaPago;
		this.prendas = prendas;
		this.perchas = perchas;
		this.total = total;
		this.estado = estado;
	}

	public Factura(Clientes clientes, Date fecha, Date fechaPago, Date fechaEntrega, int prendas, int perchas,float total, boolean estado) {
		this.clientes = clientes;
		this.fecha = fecha;
		this.fechaPago = fechaPago;
		this.fechaEntrega = fechaEntrega;
		this.prendas = prendas;
		this.perchas = perchas;
		this.total = total;
		this.estado = estado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	public int getPrendas() {
		return this.prendas;
	}

	public void setPrendas(int prendas) {
		this.prendas = prendas;
	}

	public int getPerchas() {
		return this.perchas;
	}

	public void setPerchas(int perchas) {
		this.perchas = perchas;
	}

	public float getTotal() {
		return this.total;
	}

	public void setTotal(float total) {
		this.total = total;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

}
