package TablasBD;
// Generated 09-ago-2017 11:57:13 by Hibernate Tools 3.5.0.Final

/**
 * Perchero generated by hbm2java
 */
@SuppressWarnings("serial")
public class Perchero implements java.io.Serializable {

	private Integer id;
	private Factura factura;
	private Clientes clientes;
	private boolean estado;

	public Perchero() {
	}

	public Perchero(boolean estado) {
		this.estado = estado;
	}

	public Perchero(Factura factura, Clientes clientes, boolean estado) {
		this.factura = factura;
		this.clientes = clientes;
		this.estado = estado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

}
