package TablasBD;
// Generated 12-abr-2017 22:29:04 by Hibernate Tools 3.4.0.CR1

/**
 * Perchero generated by hbm2java
 */
public class Perchero implements java.io.Serializable {

	private Integer id;
	private Clientes clientes;
	private boolean estado;

	public Perchero() {
	}

	public Perchero(boolean estado) {
		this.estado = estado;
	}

	public Perchero(Clientes clientes, boolean estado) {
		this.clientes = clientes;
		this.estado = estado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

}
