package TablasBD;
// Generated 09-ago-2017 11:57:13 by Hibernate Tools 3.5.0.Final

/**
 * Servicio generated by hbm2java
 */
@SuppressWarnings("serial")
public class Servicio implements java.io.Serializable {

	private int id;
	private String descripcion;
	private float precio;

	public Servicio() {
	}

	public Servicio(int id, String descripcion, float precio) {
		this.id = id;
		this.descripcion = descripcion;
		this.precio = precio;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getPrecio() {
		return this.precio;
	}

	public void setPrecio(float precio) {
		this.precio = precio;
	}

}
