package TablasBD;
// Generated 25-jul-2017 18:49:21 by Hibernate Tools 3.5.0.Final

/**
 * UsuariosLogin generated by hbm2java
 */
public class UsuariosLogin implements java.io.Serializable {

	private String usuario;
	private String pass;
	private int acceso;

	public UsuariosLogin() {
	}

	public UsuariosLogin(String usuario, String pass, int acceso) {
		this.usuario = usuario;
		this.pass = pass;
		this.acceso = acceso;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public int getAcceso() {
		return this.acceso;
	}

	public void setAcceso(int acceso) {
		this.acceso = acceso;
	}

}
